-- Удаляем таблицы, если они существуют
DROP TABLE IF EXISTS "user", habit, sub_habit CASCADE;

-- Создаем таблицу пользователей (AppUser)
CREATE TABLE IF NOT EXISTS "user" (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ID пользователя
username VARCHAR(255) NOT NULL,  -- Имя пользователя
email VARCHAR(255) NOT NULL UNIQUE,  -- Email (уникальный)
password VARCHAR(255) NOT NULL,  -- Пароль
role VARCHAR(50) NOT NULL  -- Роль пользователя (например, ADMIN, USER)
);

-- Создаем таблицу привычек (Habit)
CREATE TABLE IF NOT EXISTS habit (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ID привычки
name VARCHAR(255) NOT NULL UNIQUE,  -- Название привычки (уникальное)
completed_count INT NOT NULL DEFAULT 0,  -- Количество выполнений привычки
user_id BIGINT NOT NULL,  -- Внешний ключ на пользователя
CONSTRAINT fk_habit_to_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE  -- Связь с таблицей пользователей
);

-- Создаем таблицу подпривычек (SubHabit)
CREATE TABLE IF NOT EXISTS sub_habit (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ID подпривычки
name VARCHAR(255) NOT NULL,  -- Название подпривычки
completed_count INT NOT NULL DEFAULT 0,  -- Количество выполнений подпривычки
habit_id BIGINT NOT NULL,  -- Внешний ключ на привычку
CONSTRAINT fk_sub_habit_to_habit FOREIGN KEY (habit_id) REFERENCES habit (id) ON DELETE CASCADE  -- Связь с таблицей привычек
);

-- Индексы для ускорения запросов
CREATE INDEX idx_user_email ON "user" (email);
CREATE INDEX idx_habit_user_id ON habit (user_id);
CREATE INDEX idx_sub_habit_habit_id ON sub_habit (habit_id);